### ISSUE TITLE
Include OpenCV native library for linux-armv7a in binary distribution package and dcm4che-jboss-modules.(zip|tar.gz)

### ISSUE THREAD

**Issue by antoniotorres** [dcm4che/jai-imageio-jboss-modules#1]
DCM4CHEE would not start because of missing opencv library on armv7a (Raspberry Pi 4).

```bash
...
2021-12-01 15:34:01,901 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 106) WFLYUT0021: Registered web context: '/dcm4chee-arc' for server 'default-server'
2021-12-01 15:34:03,947 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 84) MSC000001: Failed to start service jboss.deployment.subunit."dcm4chee-arc-ear-5.24.2-psql.ear"."dcm4chee-arc-service-5.24.2.jar".component.ArchiveServiceImpl.START: org.jboss.msc.service.StartException in service jboss.deployment.subunit."dcm4chee-arc-ear-5.24.2-psql.ear"."dcm4chee-arc-service-5.24.2.jar".component.ArchiveServiceImpl.START: java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance
        at org.jboss.as.ee@24.0.1.Final//org.jboss.as.ee.component.ComponentStartService$1.run(ComponentStartService.java:57)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)
Caused by: java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance
        at org.jboss.as.ee@24.0.1.Final//org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:170)
        at org.jboss.as.ee@24.0.1.Final//org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:141)
        at org.jboss.as.ee@24.0.1.Final//org.jboss.as.ee.component.BasicComponent.createInstance(BasicComponent.java:88)
        at org.jboss.as.ejb3@24.0.1.Final//org.jboss.as.ejb3.component.singleton.SingletonComponent.getComponentInstance(SingletonComponent.java:127)
        at org.jboss.as.ejb3@24.0.1.Final//org.jboss.as.ejb3.component.singleton.SingletonComponent.start(SingletonComponent.java:141)
        at org.jboss.as.ee@24.0.1.Final//org.jboss.as.ee.component.ComponentStartService$1.run(ComponentStartService.java:54)
        ... 8 more
Caused by: javax.ejb.EJBException: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke private void org.dcm4chee.arc.impl.ArchiveDeviceProducer.init() on org.dcm4chee.arc.impl.ArchiveDeviceProducer@ea3b80
at org.jboss.as.ejb3@24.0.1.Final//org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:268)
        at org.jboss.as.ejb3@24.0.1.Final//org.jboss.as.ejb3.tx.CMTTxInterceptor.requiresNew(CMTTxInterceptor.java:416)
        at org.jboss.as.ejb3@24.0.1.Final//org.jboss.as.ejb3.tx.LifecycleCMTTxInterceptor.processInvocation(LifecycleCMTTxInterceptor.java:68)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.weld@24.0.1.Final//org.jboss.as.weld.injection.WeldInjectionContextInterceptor.processInvocation(WeldInjectionContextInterceptor.java:43)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ejb3@24.0.1.Final//org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ee@24.0.1.Final//org.jboss.as.ee.concurrent.ConcurrentContextInterceptor.processInvocation(ConcurrentContextInterceptor.java:45)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.ContextClassLoaderInterceptor.processInvocation(ContextClassLoaderInterceptor.java:60)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ejb3@24.0.1.Final//org.jboss.as.ejb3.component.singleton.StartupCountDownInterceptor.processInvocation(StartupCountDownInterceptor.java:25)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53)
        at org.jboss.as.ee@24.0.1.Final//org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:168)
        ... 13 more
Caused by: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke private void org.dcm4chee.arc.impl.ArchiveDeviceProducer.init() on org.dcm4chee.arc.impl.ArchiveDeviceProducer@ea3b80
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:85)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.postConstruct(DefaultLifecycleCallbackInvoker.java:66)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.injection.producer.BasicInjectionTarget.postConstruct(BasicInjectionTarget.java:122)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:174)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:96)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:140)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:694)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.injection.producer.AbstractMemberProducer.getReceiver(AbstractMemberProducer.java:123)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.injection.producer.AbstractMemberProducer.produce(AbstractMemberProducer.java:158)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.bean.AbstractProducerBean.create(AbstractProducerBean.java:180)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.contexts.unbound.DependentContextImpl.get(DependentContextImpl.java:64)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:694)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.manager.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:794)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.injection.FieldInjectionPoint.inject(FieldInjectionPoint.java:92)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.util.Beans.injectBoundFields(Beans.java:345)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.util.Beans.injectFieldsAndInitializers(Beans.java:356)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.injection.producer.DefaultInjector$1.proceed(DefaultInjector.java:71)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:48)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.injection.producer.DefaultInjector.inject(DefaultInjector.java:73)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.module.ejb.DynamicInjectionPointInjector.inject(DynamicInjectionPointInjector.java:61)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.module.ejb.SessionBeanInjectionTarget.inject(SessionBeanInjectionTarget.java:138)
        at org.jboss.as.weld@24.0.1.Final//org.jboss.as.weld.injection.WeldInjectionContext.inject(WeldInjectionContext.java:39)
        at org.jboss.as.weld@24.0.1.Final//org.jboss.as.weld.injection.WeldInjectionInterceptor.processInvocation(WeldInjectionInterceptor.java:51)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
at org.jboss.as.weld@24.0.1.Final//org.jboss.as.weld.injection.WeldInjectionContext.inject(WeldInjectionContext.java:39)
        at org.jboss.as.weld@24.0.1.Final//org.jboss.as.weld.injection.WeldInjectionInterceptor.processInvocation(WeldInjectionInterceptor.java:51)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ee@24.0.1.Final//org.jboss.as.ee.component.ManagedReferenceFieldInjectionInterceptorFactory$ManagedReferenceFieldInjectionInterceptor.processInvocation(ManagedReferenceFieldInjectionInterceptorFactory.java:112)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ee@24.0.1.Final//org.jboss.as.ee.component.ManagedReferenceFieldInjectionInterceptorFactory$ManagedReferenceFieldInjectionInterceptor.processInvocation(ManagedReferenceFieldInjectionInterceptorFactory.java:112)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ee@24.0.1.Final//org.jboss.as.ee.component.AroundConstructInterceptorFactory$1.processInvocation(AroundConstructInterceptorFactory.java:28)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.weld@24.0.1.Final//org.jboss.as.weld.injection.WeldInterceptorInjectionInterceptor.processInvocation(WeldInterceptorInjectionInterceptor.java:56)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.weld@24.0.1.Final//org.jboss.as.weld.interceptors.Jsr299BindingsCreateInterceptor.processInvocation(Jsr299BindingsCreateInterceptor.java:111)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ee@24.0.1.Final//org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ejb3@24.0.1.Final//org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:254)
        ... 28 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:83)
        ... 68 more
Caused by: java.lang.UnsatisfiedLinkError: no opencv_java in java.library.path: [/usr/java/packages/lib, /lib, /usr/lib]
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
        at java.base/java.lang.System.loadLibrary(System.java:1873)
        at org.dcm4che.imageio@5.24.2//org.opencv.osgi.OpenCVNativeLoader.init(OpenCVNativeLoader.java:17)
        at org.dcm4che.imageio@5.24.2//org.dcm4che3.opencv.NativeJLSImageWriter.<clinit>(NativeJLSImageWriter.java:79)
        at org.dcm4che.imageio@5.24.2//org.dcm4che3.opencv.NativeJLSImageWriterSpi.createWriterInstance(NativeJLSImageWriterSpi.java:81)
        at java.desktop/javax.imageio.spi.ImageWriterSpi.createWriterInstance(ImageWriterSpi.java:351)
        at java.desktop/javax.imageio.ImageIO$ImageWriterIterator.next(ImageIO.java:849)
        at java.desktop/javax.imageio.ImageIO$ImageWriterIterator.next(ImageIO.java:833)
        at org.dcm4che.imageio@5.24.2//org.dcm4che3.imageio.codec.ImageWriterFactory.getImageWriterFromImageIOServiceRegistry(ImageWriterFactory.java:245)
        at org.dcm4che.imageio@5.24.2//org.dcm4che3.imageio.codec.ImageWriterFactory.getImageWriter(ImageWriterFactory.java:237)
        at deployment.dcm4chee-arc-ear-5.24.2-psql.ear.dcm4chee-arc-service-5.24.2.jar//org.dcm4chee.arc.impl.ArchiveDeviceProducer.initImageWriterFactory(ArchiveDeviceProducer.java:192)
        at deployment.dcm4chee-arc-ear-5.24.2-psql.ear.dcm4chee-arc-service-5.24.2.jar//org.dcm4chee.arc.impl.ArchiveDeviceProducer.init(ArchiveDeviceProducer.java:111)
        ... 73 more

2021-12-01 15:34:04,183 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "dcm4chee-arc-ear-5.24.2-psql.ear")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.subunit.\"dcm4chee-arc-ear-5.24.2-psql.ear\".\"dcm4chee-arc-service-5.24.2.jar\".component.ArchiveServiceImpl.START" => "java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance
    Caused by: java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance
    Caused by: javax.ejb.EJBException: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke private void org.dcm4chee.arc.impl.ArchiveDeviceProducer.init() on org.dcm4chee.arc.impl.ArchiveDeviceProducer@ea3b80
    Caused by: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke private void org.dcm4chee.arc.impl.ArchiveDeviceProducer.init() on org.dcm4chee.arc.impl.ArchiveDeviceProducer@ea3b80
    Caused by: java.lang.reflect.InvocationTargetException
    Caused by: java.lang.UnsatisfiedLinkError: no opencv_java in java.library.path: [/usr/java/packages/lib, /lib, /usr/lib]"}}
2021-12-01 15:34:04,216 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 45) WFLYSRV0010: Deployed "dcm4chee-arc-ui2-5.24.2.war" (runtime-name : "dcm4chee-arc-ui2-5.24.2.war")
2021-12-01 15:34:04,217 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 45) WFLYSRV0010: Deployed "dcm4chee-arc-ear-5.24.2-psql.ear" (runtime-name : "dcm4chee-arc-ear-5.24.2-psql.ear")
2021-12-01 15:34:04,221 INFO  [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0183: Service status report
WFLYCTL0186:   Services which failed to start:      service jboss.deployment.subunit."dcm4chee-arc-ear-5.24.2-psql.ear"."dcm4chee-arc-service-5.24.2.jar".component.ArchiveServiceImpl.START: java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance
WFLYCTL0448: 2 additional services are down due to their dependencies being missing or failed
2021-12-01 15:34:04,563 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
2021-12-01 15:34:04,583 ERROR [org.jboss.as] (Controller Boot Thread) WFLYSRV0026: WildFly Full 24.0.1.Final (WildFly Core 16.0.1.Final) started (with errors) in 75396ms - Started 2901 of 3121 services (7 services failed or missing dependencies, 455 services are lazy, passive or on-demand)
2021-12-01 15:34:04,590 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0062: Http management interface listening on http://0.0.0.0:9990/management and https://0.0.0.0:9993/management
2021-12-01 15:34:04,591 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0053: Admin console listening on http://0.0.0.0:9990 and https://0.0.0.0:9993
```

Downloading the file manually and taking a look you can see the following structure:
```bash
curl -f http://maven.dcm4che.org/org/dcm4che/jai_imageio-jboss-modules/1.2-pre-dr-b04/jai_imageio-jboss-modules-1.2-pre-dr-b04.tar.gz | tar xz
```

![image](https://user-images.githubusercontent.com/4925102/144321914-de7475a7-47c9-4586-9cf0-d1bd125e246b.png)

The following issue presented on Raspberry Pi using [dcm4chee-arc-psql](https://github.com/dcm4che-dockerfiles/dcm4chee-arc-psql) docker image. Not sure if this is the correct repository to post the issue, but given that the issue is with the imagio module I thought it better to do it here.

**Comment by antoniotorres** [comment]
For those interested for a solution on the docker image you can add the following lines to the Dockerfile inside [dcm4chee-arc-psql](https://github.com/dcm4che-dockerfiles/dcm4chee-arc-psql)



`./Dockerfile`
```Dockerfile
...
RUN apt-get update \
    && apt-get install -y wget \
    && rm -rf /var/lib/apt/lists/*

RUN cd $JBOSS_HOME/modules/org/dcm4che/imageio/main/lib \
    && mkdir linux-armv7a \
    && cd linux-armv7a \
    && wget https://github.com/nroduit/mvn-repo/raw/master/org/weasis/thirdparty/org/opencv/libopencv_java/4.5.3-dcm/libopencv_java-4.5.3-dcm-linux-armv7a.so -O libopencv_java.so \
    && cp libopencv_java.so /usr/lib/libopencv_java.so
```

**Comment by gunterze** [comment]
s. https://github.com/dcm4che/dcm4che/issues/1069
